name: RGFRCap
channels:
  - anaconda
  - cuda 11.3
pip:
  - absl-py==0.8.1
  - appdirs==1.4.4
  - click==8.0.4
  - cycler==0.10.0
  - cytoolz==0.9.0.1
  - dataclasses==0.8
  - dill==0.3.4
  - docker-pycreds==0.4.0
  - en-core-web-sm==2.0.0
  - future==0.17.1
  - gitdb==4.0.9
  - gitpython==3.1.18
  - grpcio==1.25.0
  - h5py==2.8.0
  - importlib-metadata==4.8.3
  - kiwisolver==1.1.0
  - markdown==3.1.1
  - matplotlib==2.2.3
  - msgpack==0.6.2
  - multiprocess==0.70.9
  - numpy==1.16.4
  - pathlib==1.0.1
  - pathos==0.2.3
  - pathtools==0.1.2
  - pillow==6.2.1
  - pox==0.2.7
  - ppft==1.6.6.1
  - protobuf==3.19.6
  - psutil==5.9.4
  - pycocotools==2.0.0
  - pyparsing==2.4.5
  - python-dateutil==2.8.1
  - pytz==2019.3
  - pyyaml==6.0
  - regex==2017.4.5
  - sentry-sdk==1.24.0
  - setproctitle==1.2.3
  - smmap==5.0.0
  - tensorboard==1.14.0
  - torch==1.11.0
  - torchvision==0.12.0
  - tqdm==4.32.2
  - typing-extensions==4.1.1
  - ujson==1.35
  - urllib3==1.26.16
  - wandb==0.15.3
  - werkzeug==0.16.0
  - zipp==3.6.0
